# Site Settings
locale                   : "en-US"
title                    : "Personal website"
title_separator          : "-"
name                     : &name "Théo DUPUY"
description              : &description "PhD student in Machine Leaning"
url: "https://tdupuy2001.github.io"
baseurl: ""
repository               : "tdupuy2001/tdupuy2001.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add