# title: "Théo Dupuy"
# name: "Théo Dupuy"
# email: "theo.dupuy@mines-ales.fr"
# description: "Chercheur en ..."

url: "https://tdupuy2001.github.io"
baseurl: ""

remote_theme: academicpages/academicpages.github.io

plugins:
  - jekyll-remote-theme

author:
  name: "Théo Dupuy"
  avatar: "/assets/images/profile.jpg"
  bio: "PhD student on Machine Learning"
  location: "France"
  email: "theo.dupuy@mines-ales.fr"

navbar:
  - title: "About"
    url: /about/
  - title: "Publications"
    url: /publications/
  - title: "CV"
    url: /cv/
  - title: "Talks"
    url: /talks/