# Site settings
title: "My personal website "
name: "Théo Dupuy"
description: "Site académique personnel"
url: "https://tdupuy2001.github.io"
baseurl: "" 
locale: "en-US"
timezone: "Europe/Paris"

# Author info
author:
  name: "Théo Dupuy"
  bio: "Courte bio ici"
  avatar: "/images/profile.png"
  email: "theo.dupuy@mines-ales.fr"
  github: "ttdupuy2001"

# Collections
collections:
  publications:
    output: false #true si je veux une page par article
  talks:
    output: false

# Navigation (barre de menu)
nav:
  - title: "About"
    url: /
  - title: "Publications"
    url: /publications/
  - title: "CV"
    url: /cv/
  - title: "Talks"
    url: /talks/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Minimal styling
minimal_mistakes_skin: "default"